development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_task_dev
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_task_test
  pool: 5
  username: root
